version: '3.8'

services:
  neo4j:
    image: neo4j:5.15-community
    container_name: business-integrations-graph
    restart: unless-stopped
    
    ports:
      - "7474:7474"  # Interface Web
      - "7687:7687"  # Bolt Protocol
    
    environment:
      # Autenticação
      - NEO4J_AUTH=admin/businessgraph123
      
      # Performance  
      - NEO4J_dbms_memory_heap_max__size=2G
      - NEO4J_dbms_memory_pagecache_size=1G
      
      # Configurações de rede (para servidor externo)
      - NEO4J_dbms_default__listen__address=0.0.0.0
      - NEO4J_dbms_connector_bolt_listen__address=0.0.0.0:7687
      - NEO4J_dbms_connector_http_listen__address=0.0.0.0:7474
      
      # Configurações adicionais
      - NEO4J_dbms_logs_debug_level=INFO
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*
      - NEO4J_dbms_security_procedures_allowlist=apoc.*
      
      # APOC Plugin (para funcionalidades avançadas)
      - NEO4JLABS_PLUGINS=["apoc"]
    
    volumes:
      - business_graph_data:/data
      - business_graph_logs:/logs
      - business_graph_import:/var/lib/neo4j/import
      - ./data/import:/import
    
    healthcheck:
      test: ["CMD-SHELL", "cypher-shell -u admin -p businessgraph123 'RETURN 1'"]
      interval: 30s
      timeout: 10s  
      retries: 3
      start_period: 60s

  # Backup automático (opcional)
  backup:
    image: neo4j:5.15-community
    container_name: business-integrations-backup
    restart: "no"
    depends_on:
      - neo4j
    environment:
      - NEO4J_AUTH=admin/businessgraph123
    volumes:
      - business_graph_data:/data:ro
      - ./backups:/backups
      - ./scripts:/scripts
    command: /bin/bash -c "sleep 3600 && /scripts/backup.sh"
    profiles:
      - backup

  # Monitoring (opcional)  
  monitoring:
    image: prom/prometheus:latest
    container_name: business-integrations-monitoring
    restart: unless-stopped
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    profiles:
      - monitoring

volumes:
  business_graph_data:
    driver: local
  business_graph_logs:
    driver: local
  business_graph_import:
    driver: local
  prometheus_data:
    driver: local

networks:
  default:
    name: business-integrations-network